
# chugin name
CHUGIN_NAME=Spectacle

# all of the c/cpp files that compose this chugin
CXX_MODULES=genlib/FFTReal.cpp  genlib/Obucket.cpp  genlib/Odelay.cpp  genlib/Offt.cpp  genlib/Ooscil.cpp  genlib/RandGen.cpp
CXX_MODULES+=SpectacleBase.cpp SpectEQ.cpp Spectacle-dsp.cpp
CXX_MODULES+=Spectacle.cpp

include ../makefile.chugin
